name: Backup to S3

on:
  schedule:
    - cron: '0 0 * * *' # Adjust the cron schedule to your liking

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Backup repository
      run: |
        # Create a ZIP archive of the repository
        zip -r backup.zip .

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        # Install the AWS CLI
        curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

        # Upload the ZIP file to the S3 bucket
        aws s3 cp backup.zip s3://your-s3-bucket-name/

    - name: Cleanup
      run: |
        # Remove the ZIP file
        rm backup.zip

