name: Github Backup

on:
  push:
    branches:
    - main
    - master
  schedule:
    - cron: '* * * * *'
    
jobs:
   Backup:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v1

     
     - name: Set up environments
       run:  |
           chmod +x Backup.sh
          

     - name: Run Backup Script
       run: ./Backup.sh

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KRY }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET-KEY }}
         aws-region: us-east 1
      
           

           
