name: Github Backup

on:
  push:
    branches:
    - main
    - master
    
 jobs:
   Github Backup:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v1

     - name: Configure AWS credentials
       used: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KRY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET-ACCESS-KEY }}
         aws-region: us-east-1

      -name: Store in S3 Bucket
       run: aws s3 sync . s3://mysonpriyansh --delete
