name: Github Backup

on:
  push:
    branches:
    - main
    - master
  schedule:
    - cron: '* * * * *'
    
jobs:
   Backup:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v1

     
     - name: Set up environments
       run:  |
           chmod +x Backup.sh
           sudo apt -install -y some -dependency

     - name: Run Backup Script
       run: ./Backup.sh
       env: 
         SECRET_KEY: ${{ secrets.SECRETS }}
           

           
